# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: app
  labels:
    app: node
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: node
  type: ClusterIP