# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: app
  labels:
    app: react
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react-con
        image: uj5ghare/eng-frontend:1.29.1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always